version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Previous Visual Studio 2017
init:
- cmd: git config --global core.autocrlf true
before_build:
- cmd: >-
    dotnet --version

    nuget restore
build:
  parallel: true
  verbosity: minimal