version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Previous Visual Studio 2017
init:
- cmd: git config --global core.autocrlf true
nuget:
  project_feed: true
before_build:
- cmd: >-
    dotnet --version

    nuget restore
build:
  parallel: true
  verbosity: minimal
after_test:
- ps: >-
    dotnet pack GitObjectDb --no-build /p:Version="$ENV:APPVEYOR_BUILD_VERSION" -o ..\Artifacts
    dotnet pack GitObjectDb.Autofac --no-build /p:Version="$ENV:APPVEYOR_BUILD_VERSION" -o ..\Artifacts

    Get-ChildItem Artifacts\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }